policy:
  model_id: lerobot/smolvla_base
  device: cuda
  use_amp: true
  empty_cameras: 1

dataset:
  repo_id: smolvla_ur10e_data_v2
  video_backend: pyav

train:
  output_dir: outputs/train/smolvla_ur10e_data_v2
  job_name: smolvla_ur10e_data_v2
  seed: 1000
  batch_size: 8
  steps: 12000
  num_workers: 4
  log_freq: 100
  save_freq: 2000
