# 对应 outputs/train/smolvla_ur10e_mug_v1_b8_s8000
policy:
  model_id: lerobot/smolvla_base
  device: cuda
  use_amp: true
  empty_cameras: 1

dataset:
  repo_id: smolvla_ur10e_mug_v1
  video_backend: pyav

train:
  output_dir: outputs/train/smolvla_ur10e_mug_v1_b8_s8000
  job_name: smolvla_ur10e_mug_v1_b8_s8000
  seed: 1000
  batch_size: 8
  steps: 10000
  num_workers: 2
  log_freq: 20
  save_freq: 2000